repos:
  - repo: https://gitlab.com/flywheel-io/tools/etc/qa-ci
    rev: e5324a0ab1e27f5c579bdf5928b5e5f5ba3961ea
    hooks:
      - id: poetry_export
      - id: gearcheck
      - id: hadolint # Dockerfile linter (recommended)
      - id: jsonlint
      - id: linkcheck
      - id: markdownlint
      - id: yamllint
      - id: ruff
        args: ["--config", "pyproject.toml", --ignore, "E501"]
      - id: ruff_format
      - id: ruff_tests
      - id: pytest
